### PR TITLE
Fix lmgtfy TS2094 error.

### LINKED ISSUE #50: [reynir/lmgtfy] Fix type warnings / missing fields
Just putting this here so I won't forget.

### PR DESCRIPTION
**Pull request by reynir**
Fixes #50.

### CODE REVIEW

**Comment by kamaln7** [comment]
Thanks @reynir!

**Comment by reynir** [comment]
It's @gparent who made the fix! Thanks @gparent!

**Comment by kamaln7** [comment]
Oh, my bad. @gparent thank you!

**Comment by gparent** [comment]
\o/

**Pull request merged**
